package org.example;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import java.util.Scanner;

public class Main {

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        // Read the first sorted list
        System.out.print("Enter list1 size and elements: ");
        int size1 = scanner.nextInt();
        int[] list1 = new int[size1];
        for (int i = 0; i < size1; i++) {
            list1[i] = scanner.nextInt();
        }

        // Read the second sorted list
        System.out.print("Enter list2 size and elements: ");
        int size2 = scanner.nextInt();
        int[] list2 = new int[size2];
        for (int i = 0; i < size2; i++) {
            list2[i] = scanner.nextInt();
        }

        // Merge and print the lists
        int[] merged = merge(list1, list2);
        System.out.print("Merged list: ");
        for (int num : merged) {
            System.out.print(num + " ");
        }
        scanner.close();
    }

    public static int[] merge(int[] list1, int[] list2) {
        int[] merged = new int[list1.length + list2.length];
        int i = 0, j = 0, k = 0;

        while (i < list1.length && j < list2.length) {
            merged[k++] = (list1[i] < list2[j]) ? list1[i++] : list2[j++];
        }

        while (i < list1.length) merged[k++] = list1[i++];
        while (j < list2.length) merged[k++] = list2[j++];

        return merged;
    }
}